export const categories = [
  { slug: 'wooden-furniture', name: 'Wooden Furniture', tagline: 'Rustic & vintage', description: 'Handcrafted cabinets, chairs, tables, stools, beds, and statement pieces at market prices.', image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=900&q=80' },
  { slug: 'decor-textiles', name: 'Decor & Textiles', tagline: 'Colourful & cozy', description: 'Cushions, rugs, throws, wall hangings, mirrors, lamps, and candleholders.', image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=900&q=80' },
  { slug: 'handicrafts', name: 'Handicrafts & Antiques', tagline: 'Made with heritage', description: 'Pottery, brassware, tribal artifacts, sculptures, jewelry, and thoughtful gifts.', image: 'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=900&q=80' },
  { slug: 'wall-decor', name: 'Wall Decor & Pots', tagline: 'Finish the room', description: 'Paintings, mirrors, metal art, clocks, frames, terracotta, and ceramic pots.', image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80' },
  { slug: 'outdoor-decor', name: 'Outdoor Decor', tagline: 'Bring life outside', description: 'Planters, lanterns, garden statues, swings, and balcony accents.', image: 'https://images.unsplash.com/photo-1598902108854-10e335adac99?auto=format&fit=crop&w=900&q=80' },
];
export const products = [
  { id: 'sheesham-console', name: 'Sheesham Console', category: 'wooden-furniture', categoryLabel: 'Wooden Furniture', price: 18500, originalPrice: 24000, badge: 'Popular', image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=900&q=80', description: 'A characterful wooden console for entryways, living rooms, and collected displays.', features: ['Solid wood look', 'Hand-finished', 'Local delivery'] },
  { id: 'rustic-stool', name: 'Rustic Studio Stool', category: 'wooden-furniture', categoryLabel: 'Wooden Furniture', price: 3200, originalPrice: 4500, badge: 'Bargain', image: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=900&q=80', description: 'A compact handcrafted stool that works as seating, a side table, or a plant stand.', features: ['Compact', 'Handcrafted', 'Easy to style'] },
  { id: 'brass-lantern', name: 'Brass Heritage Lantern', category: 'handicrafts', categoryLabel: 'Handicrafts', price: 1800, originalPrice: 2600, badge: 'Handmade', image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=900&q=80', description: 'A warm brass accent inspired by traditional Indian craft and perfect for evening light.', features: ['Brass finish', 'Artisan made', 'Gift-ready'] },
  { id: 'terracotta-pot', name: 'Terracotta Garden Pot', category: 'outdoor-decor', categoryLabel: 'Outdoor Decor', price: 950, originalPrice: 1400, badge: 'New', image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=900&q=80', description: 'A textured terracotta pot for balconies, gardens, and indoor green corners.', features: ['Terracotta', 'Drainage hole', 'Indoor/outdoor'] },
  { id: 'jharokha-mirror', name: 'Jharokha Statement Mirror', category: 'wall-decor', categoryLabel: 'Wall Decor', price: 6500, originalPrice: 8900, badge: 'Statement', image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80', description: 'An ornate mirror that adds depth, craft, and a distinctly Indian focal point to a wall.', features: ['Ornate frame', 'Statement size', 'Wall-ready'] },
  { id: 'woven-rug', name: 'Handwoven Accent Rug', category: 'decor-textiles', categoryLabel: 'Decor & Textiles', price: 2800, originalPrice: 3900, badge: 'Colourful', image: 'https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=900&q=80', description: 'A colourful woven rug to bring texture and warmth to a living room or bedroom.', features: ['Handwoven', 'Easy care', 'Soft texture'] },
];
